#!/bin/bash
set -e

# Rendi NON scrivibili solo i file (non le cartelle)
find data notebooks -type f -exec chmod a-w {} +

# Cartelle di lavoro dove gli studenti scrivono output
mkdir -p work results
chmod -R a+w work results
